apiVersion: 1

datasources:
  - name: VictoriaMetrics
    uid: victoriametrics
    type: prometheus
    access: proxy
    url: ${TRACEFOX_VM_URL}
    isDefault: true
    editable: true
    jsonData:
      timeInterval: "5s"
