name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        compiler: [gcc, clang]
        mode: [release, debug]

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential gcc clang cppcheck

    - name: Build Agent
      working-directory: agent
      run: |
        make clean
        make GCC=${{ matrix.compiler }} MODE=${{ matrix.mode }}

    - name: Static Analysis
      if: matrix.compiler == 'gcc' && matrix.mode == 'release'
      working-directory: agent
      run: |
        cppcheck --enable=all --inconclusive --std=c99 --suppress=missingIncludeSystem src/ include/

    - name: Run Python Server Tests
      working-directory: server
      run: |
        python3 test_protocol.py
